# Generated by Django 5.0.7 on 2024-12-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_room_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='hostel',
            new_name='room',
        ),
    ]
